INSERT INTO burgers (title, checkout, purchased) VALUES ("Oh Cheezy Burger", 1, 0);
INSERT INTO burgers (title, checkout, purchased) VALUES ("Chicken Treat Burger", 1, 0);
INSERT INTO burgers (title, checkout, purchased) VALUES ("Oh Fish Burger", 1, 0);
INSERT INTO burgers (title, checkout, purchased) VALUES ("Supreme Tofu Burger", 0, 1);
INSERT INTO burgers (title, checkout, purchased) VALUES ("Beef XXX Burger", 0, 1);
INSERT INTO burgers (title, checkout, purchased) VALUES ("Nothing", 1, 0);

INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Chilli Lava", 9, 0, 0, 1, 1.20);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Tangy Mayo", 3, 0, 0, 1, 0.80);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Buffalo Tomato", 6, 0, 0, 1, 0.60);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Jalapeno",5, 0, 1, 0, 2.50); 
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Tomato", 0, 0, 1, 0, 1.00);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Pickles", 4, 0, 1, 0, 2.00);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Onions", 3, 0, 1, 0, 0.30);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Lettuce", 0, 0, 1, 0, 0.30); 
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Cheese", 2, 0, 1, 0, 1.20);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Oh!Good Tofu", 9, 1, 0, 0, 4.50);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("BBQ Fish Bandeau", 7, 1, 0, 0, 7.20); 
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Burnt Chicken Steak", 4, 1, 0, 0, 6.00);
INSERT INTO ingredients (name, spiceLvL, patty, topping, sauce, price) VALUES ("Beef XXX", 6, 1, 0, 0, 8.50);

INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (1, 3);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (1, 6);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (1, 7);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (1, 9);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (1, 13);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (2, 2);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (2, 5);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (2, 8);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (2, 9);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (2, 12);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (3, 1);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (3, 4);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (3, 8);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (3, 8);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (3, 11);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (4, 1);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (4, 4);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (4, 6);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (4, 7);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (4, 10);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 1);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 4);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 5);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 6);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 7);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 8);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 9);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (5, 13);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (6, 1);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (6, 6);
INSERT INTO burgerOrder (burgerID, ingredientID) VALUES (6, 9);      